// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.25.1
// source: protos/payment.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentId *string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,def=p1" json:"payment_id,omitempty"`
	Amount    *int32  `protobuf:"varint,2,opt,name=amount,def=57" json:"amount,omitempty"`
}

// Default values for Payment fields.
const (
	Default_Payment_PaymentId = string("p1")
	Default_Payment_Amount    = int32(57)
)

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_protos_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_protos_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_protos_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetPaymentId() string {
	if x != nil && x.PaymentId != nil {
		return *x.PaymentId
	}
	return Default_Payment_PaymentId
}

func (x *Payment) GetAmount() int32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return Default_Payment_Amount
}

var File_protos_payment_proto protoreflect.FileDescriptor

var file_protos_payment_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x48,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0a, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x02, 0x70,
	0x31, 0x52, 0x09, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x02, 0x35, 0x37,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73,
}

var (
	file_protos_payment_proto_rawDescOnce sync.Once
	file_protos_payment_proto_rawDescData = file_protos_payment_proto_rawDesc
)

func file_protos_payment_proto_rawDescGZIP() []byte {
	file_protos_payment_proto_rawDescOnce.Do(func() {
		file_protos_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_payment_proto_rawDescData)
	})
	return file_protos_payment_proto_rawDescData
}

var file_protos_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_payment_proto_goTypes = []any{
	(*Payment)(nil), // 0: models.Payment
}
var file_protos_payment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_payment_proto_init() }
func file_protos_payment_proto_init() {
	if File_protos_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_payment_proto_goTypes,
		DependencyIndexes: file_protos_payment_proto_depIdxs,
		MessageInfos:      file_protos_payment_proto_msgTypes,
	}.Build()
	File_protos_payment_proto = out.File
	file_protos_payment_proto_rawDesc = nil
	file_protos_payment_proto_goTypes = nil
	file_protos_payment_proto_depIdxs = nil
}
