// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.25.1
// source: protos/order2.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus2 int32

const (
	OrderStatus2_ORDER_STATUS2_PENDING    OrderStatus2 = 1
	OrderStatus2_ORDER_STATUS2_PROCESSING OrderStatus2 = 2
	OrderStatus2_ORDER_STATUS2_SHIPPED    OrderStatus2 = 3
	OrderStatus2_ORDER_STATUS2_DELIVERED  OrderStatus2 = 4
)

// Enum value maps for OrderStatus2.
var (
	OrderStatus2_name = map[int32]string{
		1: "ORDER_STATUS2_PENDING",
		2: "ORDER_STATUS2_PROCESSING",
		3: "ORDER_STATUS2_SHIPPED",
		4: "ORDER_STATUS2_DELIVERED",
	}
	OrderStatus2_value = map[string]int32{
		"ORDER_STATUS2_PENDING":    1,
		"ORDER_STATUS2_PROCESSING": 2,
		"ORDER_STATUS2_SHIPPED":    3,
		"ORDER_STATUS2_DELIVERED":  4,
	}
)

func (x OrderStatus2) Enum() *OrderStatus2 {
	p := new(OrderStatus2)
	*p = x
	return p
}

func (x OrderStatus2) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus2) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_order2_proto_enumTypes[0].Descriptor()
}

func (OrderStatus2) Type() protoreflect.EnumType {
	return &file_protos_order2_proto_enumTypes[0]
}

func (x OrderStatus2) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OrderStatus2) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OrderStatus2(num)
	return nil
}

// Deprecated: Use OrderStatus2.Descriptor instead.
func (OrderStatus2) EnumDescriptor() ([]byte, []int) {
	return file_protos_order2_proto_rawDescGZIP(), []int{0}
}

type Order2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId *string       `protobuf:"bytes,1,req,name=order_id,json=orderId" json:"order_id,omitempty"`
	Amount  *float64      `protobuf:"fixed64,2,req,name=amount" json:"amount,omitempty"`
	Status  *OrderStatus2 `protobuf:"varint,3,req,name=status,enum=models.OrderStatus2" json:"status,omitempty"`
}

func (x *Order2) Reset() {
	*x = Order2{}
	mi := &file_protos_order2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order2) ProtoMessage() {}

func (x *Order2) ProtoReflect() protoreflect.Message {
	mi := &file_protos_order2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order2.ProtoReflect.Descriptor instead.
func (*Order2) Descriptor() ([]byte, []int) {
	return file_protos_order2_proto_rawDescGZIP(), []int{0}
}

func (x *Order2) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *Order2) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *Order2) GetStatus() OrderStatus2 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return OrderStatus2_ORDER_STATUS2_PENDING
}

var File_protos_order2_proto protoreflect.FileDescriptor

var file_protos_order2_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x32, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x69, 0x0a,
	0x06, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x7f, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x52, 0x44, 0x45,
	0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x32, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x32, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x32, 0x5f, 0x53, 0x48, 0x49, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x32, 0x5f, 0x44, 0x45,
	0x4c, 0x49, 0x56, 0x45, 0x52, 0x45, 0x44, 0x10, 0x04, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73,
}

var (
	file_protos_order2_proto_rawDescOnce sync.Once
	file_protos_order2_proto_rawDescData = file_protos_order2_proto_rawDesc
)

func file_protos_order2_proto_rawDescGZIP() []byte {
	file_protos_order2_proto_rawDescOnce.Do(func() {
		file_protos_order2_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_order2_proto_rawDescData)
	})
	return file_protos_order2_proto_rawDescData
}

var file_protos_order2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_order2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_order2_proto_goTypes = []any{
	(OrderStatus2)(0), // 0: models.OrderStatus2
	(*Order2)(nil),    // 1: models.Order2
}
var file_protos_order2_proto_depIdxs = []int32{
	0, // 0: models.Order2.status:type_name -> models.OrderStatus2
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_order2_proto_init() }
func file_protos_order2_proto_init() {
	if File_protos_order2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_order2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_order2_proto_goTypes,
		DependencyIndexes: file_protos_order2_proto_depIdxs,
		EnumInfos:         file_protos_order2_proto_enumTypes,
		MessageInfos:      file_protos_order2_proto_msgTypes,
	}.Build()
	File_protos_order2_proto = out.File
	file_protos_order2_proto_rawDesc = nil
	file_protos_order2_proto_goTypes = nil
	file_protos_order2_proto_depIdxs = nil
}
